### ISSUE TITLE
Implement JPA support

### ISSUE THREAD

**Issue by headliner85** [ydb-platform/ydb-java-sdk#133]
There was attempt in v1, but not completed.

https://github.com/yandex-cloud/ydb-java-sdk/tree/master/spring-data-jpa/src/main/java/com/yandex/ydb/spring/jpa

It would be great to have jpa support and not to write full queries by hand.

**Comment by KirillKurdyukov** [comment]
Start experienced dialect https://github.com/KirillKurdyukov/ydb-hibernate/tree/main

**Comment by KirillKurdyukov** [comment]
https://github.com/ydb-platform/ydb-java-dialects/issues/1
https://github.com/ydb-platform/ydb-java-dialects/issues/2

**Comment by KirillKurdyukov** [comment]
https://github.com/ydb-platform/ydb-java-dialects
