### ISSUE TITLE
Implement Datasource interface from JDBC driver

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-java-sdk#20]
Similar to [Clickhouse JDBC driver](https://github.com/ClickHouse/clickhouse-jdbc/blob/42b1b2193931dc68b86cb5dfc86392d4c6d6601b/clickhouse-jdbc/README.md)

**Comment by alex268** [comment]
Dublicate of https://github.com/ydb-platform/ydb-jdbc-driver/issues/1
