### ISSUE TITLE
Add support of OAuth 2.0 Token Exchange

### ISSUE THREAD

**Issue by alex268** [ydb-platform/ydb-java-sdk#272]
Need to implement new credential providers based on https://www.rfc-editor.org/rfc/rfc8693

**Comment by alexv-smirnov** [comment]
Consider the reference implementation here, for consistent user experience between other language SDKs: https://github.com/ydb-platform/ydb-python-sdk/blob/main/examples/oauth2-token-exchange-credentials/main.py#L39
