### ISSUE TITLE
Add support for JOOQ

### ISSUE THREAD

**Issue by alex268** [ydb-platform/ydb-java-sdk#52]

**Comment by ikriushenkov** [comment]
I have planned the implementation of this task as a student paper and expect to complete it in the next couple of months

**Comment by alex268** [comment]
> I have planned the implementation of this task as a student paper and expect to complete it in the next couple of months

You can get [jooq-support-module](https://github.com/ydb-platform/ydb-java-dialects/tree/main/jooq-support-module) as the start point for your impementation
